// TheWizardOfWebsites/frontend/src/components/Application/Edit/Edit.jsx
import styles from "./Edit.module.css";
// import { useState } from "react";
export const Edit = () => {
  return (
    <div className={styles.containerEditForm}>
      <form className={styles.editForm} method="post" action="">
        <div>
          <label htmlFor="image" className={styles.editSiteLabel}>
            Image
          </label>
          <input
            type="file"
            accept="image/*"
            className={styles.editSiteInput}
          />
        </div>
        <div>
          <label htmlFor="title" className={styles.editSiteLabel}>
            Title
          </label>
          <input type="text" name="title" className={styles.editSiteInput} />
        </div>

        <div>
          <label htmlFor="price" className={styles.editSiteLabel}>
            Price
          </label>
          <input type="text" name="price" className={styles.editSiteInput} />
        </div>
        <div>
          <label htmlFor="short-description" className={styles.editSiteLabel}>
            Short description
          </label>
          <input
            type="text"
            name="short-description"
            className={styles.editSiteInput}
          />
        </div>
        <div>
          <label htmlFor="description" className={styles.editSiteLabel}>
            Description
          </label>
          <textarea
            name="description"
            rows="4"
            cols="50"
            className={styles.editSiteTextarea}
          />
        </div>

        <button className={styles.editSiteButton}>Edit</button>
      </form>
    </div>
  );
};

// HealthyAndDelicious/HealthyAndDeliciousAngular/src/app/recipes/edit/edit.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.css']
})
export class EditComponent {

}

<div class="container-edit-recipe">
  <form class="edit-recipe-form" method="post" action="">
    <div>
      <label for="image" class="edit-recipe-label">
        Image
      </label>
      <input type="text" class="edit-recipe-input" name="image" placeholder="Upload image" />
    </div>
    <div>
      <label for="title" class="edit-recipe-label">
        Title
      </label>
      <input type="text" name="title" placeholder="Enter recipe title" class="edit-recipe-input" />
    </div>

    <div>
      <label for="description" class="edit-recipe-label">
        Description
      </label>
      <textarea name="description" rows="4" cols="50" placeholder="Enter recipe description"
        class="edit-recipe-textarea"></textarea>
    </div>

    <div>
      <label for="ingredients" class="edit-recipe-label">
        Ingredients
      </label>
      <textarea name="ingredients" rows="4" cols="50" placeholder="Enter recipe ingredients"
        class="edit-recipe-textarea"></textarea>
    </div>

    <button type="submit" class="edit-recipe-button">Edit</button>
  </form>
</div>
